export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'
export const TOGGLE_RANDOM = 'TOGGLE_RANDOM'
export const TOGGLE_REPEAT = 'TOGGLE_OPTIONS'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'

export const FETCH_BEAT_UPLOAD = 'FETCH_BEAT_UPLOAD'
export const SHOW_AUDIOPLAYER = 'SHOW_AUDIOPLAYER'
export const TOGGLE_PLAYBUTTON = 'TOGGLE_PLAYBUTTON'
export const SETVOLUME = 'SETVOLUME'
export const SETDURATION = 'SETDURATION'
export const SET_TIME = 'SET_TIME'
// export const TOGGLE_PLAYBUTTON = 'TOGGLE_PLAYBUTTON'

export const FETCH_BEAT_UPLOAD_FAIL = 'FETCH_BEAT_UPLOAD_FAIL'

export const FETCH_SELL = 'FETCH_SELL'
export const FETCH_SELL_FAIL = 'FETCH_SELL_FAIL'

export const FETCH_SINGLE_BEAT = 'FETCH_SINGLE_BEAT'
export const FETCH_SINGLE_BEAT_FAIL = 'FETCH_SINGLE_BEAT_FAIL'

